# Generated by Django 4.0.5 on 2022-06-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schools',
            name='address',
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.TimeField(max_length=200),
        ),
    ]
